cartpole:
  task: realworld_swingup
  safety_spec:
    enable: True
    observations: True
    safety_coeff: 0.3
    constraints: slider_pos_constraint
    
  perturb_spec:
    enable: False
    period: 0
    scheduler: constant