cartpole:
  task: realworld_swingup
  safety_spec:
    enable: True
    observations: True
    safety_coeff: 0.3
  constraints:
    - slider_pos_constraint
  perturb_spec:
    enable: True
    period: 1
    scheduler: uniform
    param: pole_length
    min: 0.75
    max: 1.25
