name: asmbrl
replay_buffer:
  batch_size: 32
  sequence_length: 32
  num_shots: 4
  capacity: 1000
model:
  n_layers: 3
  hidden_size: 64
model_optimizer:
  lr: 1e-3
  eps: 1e-5
  clip: 0.5
plan_horizon: 15
replan_every: 1
discount: 0.99
lambda_: 0.97
actor_critic_update_steps: 100
actor:
  n_layers: 2
  hidden_size: 128
critic:
  n_layers: 2
  hidden_size: 128
actor_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
critic_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
update_steps: 200
pacoh:
  num_examples: 200
  n_particles: 3
  posterior_stddev: 0.5
  n_prior_samples: 5
  prior_weight: 1e-3
  bandwidth: 10.
posterior:
  update_steps: 250
  num_examples: 250
  n_prior_samples: 1
  learning_rate: 3e-4
  prior_weight: 1e-3
  bandwidth: 10.
