name: asmbrl
replay_buffer:
  batch_size: 128
  sequence_length: 64
  num_shots: 4
  capacity: 1000
model:
  n_layers: 2
  hidden_size: 128
model_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
plan_horizon: 15
update_steps: 100
replan_every: 1
cem:
  num_particles: 50
  num_iters: 3
  num_elite: 10
  stop_cond: 0.1
pacoh:
  n_particles: 5
  posterior_stddev: 0.3
  n_prior_samples: 2
  prior_weight: 0.
  bandwidth: 10.
posterior:
  update_steps: 100
  n_prior_samples: 2
  learning_rate: 1e-3
  prior_weight: 0.
  bandwidth: 10.
