name: fsmbrl
replay_buffer:
  batch_size: 32
  sequence_length: 32
  num_shots: 4
  capacity: 1000
model:
  n_layers: 3
  hidden_size: 64
  hippo_n: 16

model_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
plan_horizon: 15
replan_every: 1
cem:
  num_particles: 100
  num_iters: 10
  num_elite: 10
  stop_cond: 0.1
update_steps: 100
