name: smbrl
replay_buffer:
  batch_size: 32
  sequence_length: 64
  num_shots: 4
  capacity: 1000
model:
  n_layers: 2
  hidden_size: 128
actor:
  n_layers: 2
  hidden_size: 128
  init_stddev: 5.
critic:
  n_layers: 2
  hidden_size: 128
actor_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
critic_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
model_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
discount: 0.99
lambda_: 0.97
plan_horizon: 15
update_steps: 100
