name: smbrl
replay_buffer:
  batch_size: 128
  sequence_length: 64
  num_shots: 4
  capacity: 1000
model:
  n_layers: 2
  hidden_size: 128
replan_every: 1
model_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
cem:
  num_particles: 100
  num_iters: 10
  num_elite: 10
  stop_cond: 0.1
plan_horizon: 15
update_steps: 100
