defaults:
  - _self_
  - agents: smbrl
  - tasks: pendulum

hydra:
  run:
    dir: ${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  sweep:
    dir: ${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir

log_dir: output

training:
  safe: True
  cost_limit: 25
  seed: 0
  time_limit: 200
  episodes_per_task: 10
  eval_episodes_per_task: 10
  adaptation_budget: 1
  epochs: 200
  eval_every: 5
  action_repeat: 1
  render_episodes: 1
  precision: 32
  parallel_envs: 20
  task_batch_size: 20
  scale_reward: 1.
  num_tasks: 5
