defaults:
  - agents: smbrl

training:
  safe: True
  cost_limit: 25
  log_dir: results
  seed: 0
  time_limit: 1000
  episodes_per_task: 10
  eval_episodes_per_task: 10
  adaptation_budget: 1
  epochs: 200
  eval_every: 5
  action_repeat: 1
  render_episodes: 1
  render_options: { camera_id: "fixedfar" }
  jit: True
  precision: 32
  parallel_envs: 20
  task_batch_size: 20
  scale_reward: 1.
