defaults:
  - _self_
  - agent: smbrl
  - environment: pendulum_direction

hydra:
  run:
    dir: ${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/${hydra.job.name}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
    chdir: true

log_dir: outputs

training:
  safe: True
  cost_limit: 25
  seed: 0
  time_limit: 1000
  episodes_per_task: 10
  eval_episodes_per_task: 10
  adaptation_budget: 1
  epochs: 200
  eval_every: 5
  action_repeat: 1
  render_episodes: 1
  precision: 32
  parallel_envs: 20
  task_batch_size: 20
  scale_reward: 1.
  num_tasks: 20
